sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "8"
script:
  - npm run build
  - npm run lint
  - npm test
  - npm run spec
# deploy:
#   provider: npm
#   email: [NPM_EMAIL_ADDRESS]
#   api_key: [NPM_AUTH_TOKEN]
after_success:
  - .travis/after_success.sh
  - npm run send-coverage
git:
  depth: 1