sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "8"
script:
  - npm run build
  - npm run lint
  - npm test
  - npm run spec
after_success:
  - npm run send-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/