sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "8"
script:
  - npm run lint
  - npm test
  - npm run spec
  - npm run build-prod
after_success:
  - npm run send-coverage
  - npm run semantic-release
git:
  depth: 1