sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "8"
# before_install: .travis/before_install.sh
# after_script: npm run send-coverage
# after_success: .travis/after_success.sh
script: npm run lint && npm test && npm run spec
git:
  depth: 1